name=NPM1300
author=Albert Niyonsenga
maintainer=Albert Niyonsenga
sentence=Arduino port of NPM1300 driver
paragraph=This library allows to easily configure the NPM1300 PMIC from Nordic Semiconductors
category=Sensors
url=https://github.com/aburt2/npmx
architectures=*
includes=src/npm1300.hpp
version=0.0.1
